Repository GSM-MSG/GCMS-FrontEnd-V2, pull requests merged in 2023-03, with the labels that each got.

#185 🔀 클럽리스트 클럽옵션 스타일 수정
  components/ClubList/style.ts
Labels: ⚡️ Simple

#186 🔀 content 값 검증 추가
  components/ClubCreationModal/Page/ClubContent.tsx
Labels: 2️⃣ Priority: Medium, 🐞 Bug

#188 🔀 멤버페이지에서 디테일 가는 링크 추가
  components/Common/ClubNav/index.tsx
  components/Common/ClubNav/style.ts
Labels: ⚡️ Simple, ✨ Feature

#190 🔀 동아리 생성시 이미 업로드 문제 해결
  components/ClubCreationModal/Page/ClubImgUpload.tsx
  components/Common/ClubImgs/index.tsx
  store/clubCreation.ts
  store/imgs.ts
  store/index.ts
  type/components/ClubCreationModal.ts
  type/store/imgs.ts
Labels: 2️⃣ Priority: Medium, 🐞 Bug

#194 🔀 유저프로필 요청 API 추가
  components/Header/index.tsx
  components/MyPage/index.tsx
  hooks/useLoggedIn.tsx
  store/user.ts
  type/common/ProfileType.ts
  type/common/RoleType.ts
  type/common/UserProfileType.ts
  type/common/index.ts
Labels: 1️⃣ Priority: High, ✨ Feature

#195 🔀 어드민을 위한 header 추가
  assets/svg/HamburgerBar.tsx
  assets/svg/index.ts
  components/Header/index.tsx
  components/Header/style.ts
  components/Sidebar/Content.tsx
  components/Sidebar/index.tsx
  components/Sidebar/style.ts
  pages/_document.tsx
  store/index.ts
  store/sidebar.ts
  type/components/Header.ts
Labels: 1️⃣ Priority: High, ✨ Feature

#196 🔀 동아리 허가 요청 페이지 추가
  components/ClubPermissionPage/index.tsx
  components/ClubPermissionPage/style.ts
  components/Common/ClubPermissionList/index.tsx
  components/Common/ClubPermissionList/style.ts
  lib/requestClubType.ts
  mocks/handlers/api/admin/[clubID]/delete.ts
  mocks/handlers/api/admin/[clubID]/patch.ts
  mocks/handlers/api/admin/get.ts
  mocks/handlers/index.ts
  pages/permission/index.tsx
  type/components/ClubPermission.ts
Labels: ✨ Feature

#198 🔀 file-saver dependency 추가
  package.json
  yarn.lock
Labels: 1️⃣ Priority: High, ✨ Feature

#199 🔀 클럽 타입 선택 내비게이션 분리
  components/ClubList/index.tsx
  components/ClubOptionPick/index.tsx
  components/ClubOptionPick/style.ts
  type/components/ClubOptionNavigation.ts
Labels: 1️⃣ Priority: High, ♻️ Refactor

#197 🔀 어드민 학생 리스트 페이지 추가
  components/StuListPage/StuInfo/ClubItem.tsx
  components/StuListPage/StuInfo/index.tsx
  components/StuListPage/StuInfo/style.ts
  components/StuListPage/StuSearch/index.tsx
  components/StuListPage/StuSearch/style.ts
  components/StuListPage/UserList/index.tsx
  components/StuListPage/UserList/style.ts
  components/StuListPage/index.tsx
  components/StuListPage/style.ts
  pages/stulist/index.tsx
  store/index.ts
  store/uuid.ts
  type/common/AdminDetailType.ts
  type/common/AdminUserListType.ts
  type/common/ProfileType.ts
Labels: 2️⃣ Priority: Medium, ✨ Feature

#200 🔀 토큰 재발급 로직 오류
  api/TokenManager.ts
  store/reissue.ts
Labels: 1️⃣ Priority: High, 🐞 Bug

#205 🔀 디테일페이지 동아리 멤버 리스트 이미지 추가
  components/DetailPage/ClubMember.tsx
  components/DetailPage/style.ts
Labels: 2️⃣ Priority: Medium, ⚡️ Simple, ⚡️Performance

#208 🔀 동아리 생성 완료 모달 퍼블리싱
  assets/svg/Envelope.tsx
  assets/svg/index.ts
  components/ClubCreationModal/Common/Layout/index.tsx
  components/ClubCreationModal/Common/SubmitButton/index.tsx
  components/ClubCreationModal/Page/AddClubMember.tsx
  components/ClubCreationModal/Page/Confirm.style.ts
  components/ClubCreationModal/Page/Confirm.tsx
  components/ClubCreationModal/index.tsx
  components/ClubCreationModal/style.ts
  store/clubCreationPage.ts
Labels: 2️⃣ Priority: Medium, ✨ Feature

#203 🔀 프로필 모달 띄운 후 다른 곳을 클릭하면 모달이 사라지게 하는 기능 추가
  components/MyPage/ClubItem/style.ts
  components/MyPage/index.tsx
Labels: 2️⃣ Priority: Medium, ⚡️Performance

#211 🔀 header seo 최적화
  components/Header/index.tsx
  components/Header/style.ts
Labels: 2️⃣ Priority: Medium, 🐞 Bug

#213 🔀 폰트 최적화
  public/woff/Pretendard-Black.woff
  public/woff/Pretendard-Bold.woff
  public/woff/Pretendard-ExtraBold.woff
  public/woff/Pretendard-ExtraLight.woff
  public/woff/Pretendard-Light.woff
  public/woff/Pretendard-Medium.woff
  public/woff/Pretendard-Regular.woff
  public/woff/Pretendard-SemiBold.woff
  public/woff/Pretendard-Thin.woff
  public/woff2/Pretendard-Black.woff2
  public/woff2/Pretendard-Bold.woff2
  public/woff2/Pretendard-ExtraBold.woff2
  public/woff2/Pretendard-ExtraLight.woff2
  public/woff2/Pretendard-Light.woff2
  public/woff2/Pretendard-Medium.woff2
  public/woff2/Pretendard-Regular.woff2
  public/woff2/Pretendard-SemiBold.woff2
  public/woff2/Pretendard-Thin.woff2
  styles/globals.css
Labels: 2️⃣ Priority: Medium, ⚡️Performance

#206 🔀 통계페이지 제작
  assets/svg/ClassBadge.tsx
  assets/svg/Human.tsx
  assets/svg/index.ts
  components/Header/index.tsx
  components/StatisticsPage/ClubList/index.tsx
  components/StatisticsPage/ClubList/style.ts
  components/StatisticsPage/FileDownload/index.tsx
  components/StatisticsPage/FileDownload/style.ts
  components/StatisticsPage/Icon/index.tsx
  components/StatisticsPage/Icon/style.ts
  components/StatisticsPage/Statistics/index.tsx
  components/StatisticsPage/Statistics/style.ts
  components/StatisticsPage/index.tsx
  components/StatisticsPage/style.ts
  hooks/index.ts
  hooks/useExcelDownload.tsx
  pages/statistics.tsx
  type/components/Statistics.ts
Labels: 1️⃣ Priority: High, ✨ Feature

#222 🔀 동아리 이름이 길 때 처리
  components/ClubList/style.ts
Labels: 3️⃣ Priority: Low

#224 🔀 클럽 허가 요청 페이지 이슈 수정
  components/Common/ClubPermissionList/index.tsx
  components/Common/ClubPermissionList/style.ts
Labels: 1️⃣ Priority: High, 🐞 Bug

#227 🔀 어드민 학생 리스트 페이지 api요청 로직 수정
  components/StuListPage/StuInfo/index.tsx
Labels: 3️⃣ Priority: Low, ⚡️ Simple, 🐞 Bug

#221 🔀 동아리 디테일 페이지의 버튼 수정
  assets/svg/GearIcon.tsx
  components/ClubEdit/components/Notice/SwitchBtn.tsx
  components/ClubEdit/components/Notice/index.tsx
  components/Common/Switch/index.tsx
  components/Common/Switch/style.ts
  components/DetailPage/ClubName.tsx
  components/DetailPage/SideBar.tsx
  components/DetailPage/SideBtn.test.tsx
  components/DetailPage/SideBtn.tsx
  components/DetailPage/style.ts
  store/clubDetail.ts
  store/user.ts
Labels: 2️⃣ Priority: Medium

#228 🔀 confirm modal 추가
  components/ApplicantPage/ChoiceUser/index.tsx
  components/ClubEdit/components/Notice/ClubLeaveAndDeleteBtn.tsx
  components/ClubMemberPage/UserList/DelegateUser.tsx
  components/ClubMemberPage/UserList/KickUser.tsx
  components/ClubMemberPage/UserList/UserItem.tsx
  components/Common/ConfirmModal/index.tsx
  components/Common/ConfirmModal/style.ts
  components/MyPage/ProfileSetting/index.tsx
  store/confirmModal.ts
  store/index.ts
  type/common/ConfirmStateType.ts
  type/components/MyPage.ts
Labels: 2️⃣ Priority: Medium

#229 🔀 동아리 수정 페이지 디자인 수정
  components/ApplicantPage/style.ts
  components/ClubEdit/components/Notice/style.ts
  components/ClubEdit/style.ts
  components/ClubMemberPage/style.ts
Labels: 3️⃣ Priority: Low

#226 🔀 UserBox 속성명 수정
  components/ClubMemberPage/UserList/UserItem.tsx
  components/ClubMemberPage/UserList/style.ts
  components/StuListPage/UserList/index.tsx
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#223 🔀 허용되지 않은 페이지에 있을 때 메인 페이지로 이동하는 기능 추가
  components/ClubEdit/index.tsx
  components/DetailPage/SideBtn.test.tsx
  components/StuListPage/StuSearch/index.tsx
  components/StuListPage/index.tsx
  hooks/useFetch.tsx
Labels: 1️⃣ Priority: High, ✨ Feature, 🐞 Bug

#214 🔀 샘플 이미지 수정
  components/ApplicantPage/SelectedUserImg/index.tsx
  components/ApplicantPage/SelectedUserImg/style.ts
  components/ApplicantPage/UserList/UserItem.tsx
  components/ApplicantPage/UserList/style.ts
  components/ClubCreationModal/Common/Member/index.tsx
  components/ClubCreationModal/Common/Member/style.ts
  components/ClubCreationModal/Common/SelectUserList/index.tsx
  components/ClubCreationModal/Common/SelectUserList/style.ts
  components/ClubMemberPage/UserList/UserItem.tsx
  components/ClubMemberPage/UserList/style.ts
  components/Common/ProfileImg/index.tsx
  components/DetailPage/ClubMember.tsx
  components/DetailPage/Contact.tsx
  components/DetailPage/style.ts
  components/Header/Profile.tsx
  components/Header/style.ts
  components/MyPage/index.tsx
  components/StuListPage/StuInfo/index.tsx
  components/StuListPage/UserList/index.tsx
  lib/ProfileSrc.ts
  public/svg/Profile.svg
Labels: 3️⃣ Priority: Low, ⚡️ Simple, ⚡️Performance, ✨ Feature

#225 🔀 동아리 신청자 목록 페이지 수정
  components/ApplicantPage/SelectedUserImg/index.tsx
  components/ApplicantPage/SelectedUserImg/style.ts
  components/ApplicantPage/index.tsx
  store/applicant.ts
  type/store/applicant.ts
Labels: 1️⃣ Priority: High, ⚡️Performance

#232 🔀 동아리 수정 페이지 승인 권한 수정
  components/ClubEdit/index.tsx
  type/common/ScopeType.ts
Labels: 2️⃣ Priority: Medium

#230 🔀 관리자 권한 설정
  components/ApplicantPage/UserList/UserItem.tsx
  components/ApplicantPage/index.tsx
  components/ClubEdit/components/Notice/index.tsx
  components/ClubEdit/components/Notice/style.ts
  components/ClubMemberPage/UserList/UserItem.tsx
  components/CreateClubBtn/index.tsx
  components/Header/style.ts
Labels: 1️⃣ Priority: High

#234 🔀 중복 쿼리 및 서로 다른 컴포넌트 state 불일치 문제
  components/ClubEdit/components/Edit/index.tsx
  components/ClubEdit/components/Notice/index.tsx
  components/ClubEdit/index.tsx
  components/Common/ClubNav/index.tsx
  lib/DataInitializer.ts
  lib/customBaseQuery.ts
  store/ClubDetailApi.ts
  store/index.ts
Labels: 2️⃣ Priority: Medium, 🐞 Bug

#235 🔀 스크롤바 제거
  styles/globals.css
Labels: 3️⃣ Priority: Low

#236 🔀 로그인 전 상태에서 디테일 입장 불가능 오류 수정
  hooks/useFetch.tsx
  hooks/useLoggedIn.tsx
Labels: 1️⃣ Priority: High, 🐞 Bug

#238 🔀 동아리 멤버 페이지 위임, 추방 반응 추가
  components/ClubMemberPage/UserList/DelegateUser.tsx
  components/ClubMemberPage/UserList/KickUser.tsx
  components/ClubMemberPage/UserList/UserItem.tsx
  components/ClubMemberPage/UserList/index.tsx
  components/ClubMemberPage/index.tsx
  store/clubMember.ts
  store/index.ts
  type/components/MemberPage.ts
Labels: 2️⃣ Priority: Medium, 🐞 Bug

#241 🔀 동아리 디테일 페이지 문제 수정
  components/DetailPage/SideBtn.tsx
  pages/detail/[clubID].tsx
Labels: 0️⃣ Priority: Critical

#240 🔀 동아리 디테일 페이지 문제 수정
  components/DetailPage/SideBtn.tsx
  pages/detail/[clubID].tsx
Labels: 0️⃣ Priority: Critical

#252 🔀 동아리 navigation style 수정
  components/Common/ClubNav/style.ts
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#257 🔀 동아리 생성 유효성 검사 수정
  components/ClubCreationModal/Page/ClubInfoInput.tsx
Labels: 2️⃣ Priority: Medium, 🐞 Bug

#255 🔀 동아리 수정 페이지 유효성 검사 수정
  components/ClubEdit/components/Edit/index.tsx
Labels: 2️⃣ Priority: Medium, 🐞 Bug

#260 🔀 동아리 멤버 리스트에 title 추가
  pages/member/[clubID].tsx
Labels: 3️⃣ Priority: Low, 🐞 Bug

#258 🔀 디페일 페이지 동아리 설명부분이 \n이 안되는 문제 해결
  components/DetailPage/style.ts
Labels: 2️⃣ Priority: Medium

#259 🔀 통계페이지 동아리 리스트별 페이지를 구별
  components/StatisticsPage/FileDownload/index.tsx
  components/StatisticsPage/index.tsx
  pages/statistics.tsx
Labels: 2️⃣ Priority: Medium, ✨ Feature

#262 🔀 토큰 관리 로직 수정
  api/TokenManager.ts
  api/index.ts
Labels: 0️⃣ Priority: Critical

#251 🔀 동아리 신청자 페이지 권한 문제 수정
  components/ApplicantPage/index.tsx
  type/common/ApplicantListType.ts
  type/components/ApplicantPage.ts
Labels: 1️⃣ Priority: High, 🐞 Bug

#264 🔀 Deploy
  api/TokenManager.ts
  api/index.ts
  components/ApplicantPage/index.tsx
  components/ClubCreationModal/Page/ClubInfoInput.tsx
  components/ClubEdit/components/Edit/index.tsx
  components/Common/ClubNav/style.ts
  components/DetailPage/style.ts
  components/StatisticsPage/FileDownload/index.tsx
  components/StatisticsPage/index.tsx
  pages/member/[clubID].tsx
  pages/statistics.tsx
  type/common/ApplicantListType.ts
  type/components/ApplicantPage.ts
Labels: 🌏 Deploy

#266 🔀 README를 추가합니다
  README.md
  public/svg/logo.svg
Labels: 2️⃣ Priority: Medium
