Repository GSM-MSG/GCMS-FrontEnd-V2, pull requests merged in 2023-04, with the labels that each got.

#269 🔀 동아리 소개글이 잘리는 문제
  components/DetailPage/style.ts
Labels: 2️⃣ Priority: Medium

#271 🔀 노션링크 문제 해결
  components/ClubCreationModal/Page/ClubInfoInput.tsx
  components/ClubEdit/components/Edit/index.tsx
Labels: 2️⃣ Priority: Medium, 🐞 Bug

#273 🔀 이미지 우클릭 이벤트 막기
  components/ClubEdit/components/Notice/index.tsx
  components/ClubList/style.ts
  components/Common/BannerImg/index.tsx
  components/Common/ClubImgs/style.ts
  components/Common/ClubPermissionList/style.ts
  components/Common/NoCopyBox/index.tsx
  components/Common/ProfileImg/index.tsx
  components/DetailPage/ClubActivity.tsx
  components/DetailPage/ClubMember.tsx
  components/DetailPage/Contact.tsx
  components/DetailPage/index.tsx
  components/DetailPage/style.ts
  components/MyPage/ClubItem/index.tsx
  components/MyPage/style.ts
  components/StatisticsPage/ClubList/index.tsx
  components/StuListPage/StuInfo/ClubItem.tsx
Labels: 2️⃣ Priority: Medium, ⚡️Performance

#274 🔀 이미지 확대 기능 추가
  components/ClubList/ClubItem.tsx
  components/ClubList/style.ts
  components/Common/ClubImgs/index.tsx
  components/Common/ClubImgs/style.ts
  components/Common/ClubPermissionList/index.tsx
  components/Common/ClubPermissionList/style.ts
  components/Common/NoCopyBox/index.tsx
  components/DetailPage/ClubActivity.tsx
  components/DetailPage/ImageDetail.tsx
  components/DetailPage/index.tsx
  components/DetailPage/style.ts
  components/MyPage/index.tsx
  components/MyPage/style.ts
Labels: 2️⃣ Priority: Medium, ✨ Feature

#275 🔀 Deploy
  README.md
  components/ClubCreationModal/Page/ClubInfoInput.tsx
  components/ClubEdit/components/Edit/index.tsx
  components/ClubEdit/components/Notice/index.tsx
  components/ClubList/ClubItem.tsx
  components/Common/BannerImg/index.tsx
  components/Common/ClubImgs/index.tsx
  components/Common/ClubImgs/style.ts
  components/Common/ClubPermissionList/index.tsx
  components/Common/NoCopyBox/index.tsx
  components/Common/ProfileImg/index.tsx
  components/DetailPage/ClubActivity.tsx
  components/DetailPage/ClubMember.tsx
  components/DetailPage/Contact.tsx
  components/DetailPage/ImageDetail.tsx
  components/DetailPage/index.tsx
  components/DetailPage/style.ts
  components/MyPage/ClubItem/index.tsx
  components/MyPage/index.tsx
  components/StatisticsPage/ClubList/index.tsx
  components/StuListPage/StuInfo/ClubItem.tsx
  public/svg/logo.svg
Labels: 🌏 Deploy
