Repository GSM-MSG/GCMS-FrontEnd-V2, pull requests merged in 2023-02, with the labels that each got.

#5 🔀 next-redux-wrapper 8.0.0 업데이트
  pages/_app.tsx
Labels: 3️⃣ Priority: Low

#6 🔀 동아리 생성 상태관리
  store/clubCreation.test.ts
  store/clubCreation.ts
  store/index.ts
  type/common/ClubType.ts
  type/common/MemberType.ts
  type/common/index.ts
  type/store/clubCreation.ts
Labels: ✨ Feature

#9 🔀 portal 스타일 수정
  components/Portal/style.ts
Labels: 3️⃣ Priority: Low

#10 🔀 Create GCMS-CI.yml
  .github/workflows/GCMS-CI.yml
Labels: ✨ Feature

#13 🔀 마이페이지 퍼블리싱
  components/MyPage/index.tsx
  components/MyPage/style.ts
  mocks/handlers.ts
  pages/my/index.tsx
  public/svg/KebabMenuIcon.tsx
  public/svg/profileIcon.tsx
  type/common/ProfileType.ts
  type/common/index.ts
Labels: ✨ Feature

#16 클럽 생성 모달 pagination 상태관리
  store/clubCreationPage.ts
  store/index.ts
Labels: ✨ Feature

#18 🔀 svg 폴더 이동
  assets/svg/KebabMenuIcon.tsx
  assets/svg/index.ts
  assets/svg/profileIcon.tsx
  components/MyPage/index.tsx
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
Labels: 3️⃣ Priority: Low, 🐞 Bug

#19 🔀 동아리 종류 선택 modal 퍼블리싱
  components/ClubCreationModal/Layout/Navigation.style.ts
  components/ClubCreationModal/Layout/Navigation.tsx
  components/ClubCreationModal/Layout/SubmitButton.style.ts
  components/ClubCreationModal/Layout/SubmitButton.tsx
  components/ClubCreationModal/Page/ClubKindSelection.style.ts
  components/ClubCreationModal/Page/ClubKindSelection.tsx
  components/ClubCreationModal/index.tsx
  components/ClubCreationModal/style.ts
  lib/clubTypeInfo.ts
  public/png/EditorialClubHuman.png
  public/png/FreedomClubHuman.png
  public/png/MajorClubHuman.png
  type/assets/svg/XMark.tsx
  type/assets/svg/index.ts
  type/components/ClubCreationModal.ts
  type/lib/clubTypeInfo.ts
Labels: 2️⃣ Priority: Medium, ✨ Feature

#22 🔀 동아리 정보 입력 모달 퍼블리싱
  components/ClubCreationModal/Common/Input.style.ts
  components/ClubCreationModal/Common/Input.tsx
  components/ClubCreationModal/Common/Layout.style.ts
  components/ClubCreationModal/Common/Layout.tsx
  components/ClubCreationModal/Common/Navigation.style.ts
  components/ClubCreationModal/Common/Navigation.tsx
  components/ClubCreationModal/Common/SubmitButton.style.ts
  components/ClubCreationModal/Common/SubmitButton.tsx
  components/ClubCreationModal/Page/ClubInfoInput.tsx
  components/ClubCreationModal/Page/ClubKindSelection.style.ts
  components/ClubCreationModal/Page/ClubKindSelection.tsx
  components/ClubCreationModal/index.tsx
  type/components/ClubCreationModal.ts
Labels: 2️⃣ Priority: Medium, ✨ Feature

#25 🔀 msw handler 파일 구조 변경
  mocks/handlers.ts
  mocks/handlers/api/get.ts
  mocks/handlers/api/user/get.ts
  mocks/handlers/index.ts
Labels: ♻️ Refactor

#28 🔀 msw handler base url 설정
  mocks/handlers/api/get.ts
  mocks/handlers/api/user/get.ts
  mocks/handlers/serverApi.ts
Labels: 🐞 Bug

#27 🔀 axios config 생성
  api/TokenManager.ts
  api/index.ts
  lib/token.ts
  type/api/TokenManager.ts
Labels: 1️⃣ Priority: High, ⚙ Setting

#30 🔀 이미지 관리 store 생성
  store/imgs.ts
  store/index.ts
  type/store/imgs.ts
Labels: ✨ Feature

#31 🔀 imgs store 수정
  store/imgs.ts
  type/store/imgs.ts
Labels: 🐞 Bug

#34 🔀 content 입력 모달 퍼블리싱
  components/ClubCreationModal/Common/Textarea.style.ts
  components/ClubCreationModal/Common/Textarea.tsx
  components/ClubCreationModal/Page/ClubContent.tsx
  components/ClubCreationModal/index.tsx
  type/components/ClubCreationModal.ts
Labels: ✨ Feature

#32 🔀 동아리 이미지 업로드 모달 퍼블리싱
  assets/svg/Pictures.tsx
  assets/svg/XMark.tsx
  assets/svg/index.ts
  components/ClubCreationModal/Common/BannerImg.style.ts
  components/ClubCreationModal/Common/BannerImg.tsx
  components/ClubCreationModal/Common/ClubImgs.style.ts
  components/ClubCreationModal/Common/ClubImgs.tsx
  components/ClubCreationModal/Common/SubmitButton.tsx
  components/ClubCreationModal/Page/ClubImgUpload.tsx
  components/ClubCreationModal/index.tsx
  hooks/index.ts
  hooks/useUpload.tsx
  mocks/handlers/api/image/post.ts
  pages/_app.tsx
  store/clubCreation.test.ts
  store/clubCreation.ts
  store/index.ts
  type/assets/svg/index.ts
  type/components/ClubCreationModal.ts
Labels: ✨ Feature

#37 🔀 유저 멘션 기능 및 리뷰어 자동 할당 기능 추가
  .github/CODEOWNERS
  .github/workflows/GCMS-CI.yml
Labels: ✨ Feature

#36 🔀 동아리 멤버 선택 모달 퍼블리싱
  components/ClubCreationModal/Common/Input.tsx
  components/ClubCreationModal/Common/Member.style.ts
  components/ClubCreationModal/Common/Member.tsx
  components/ClubCreationModal/Common/SelectUserList.style.ts
  components/ClubCreationModal/Common/SelectUserList.tsx
  components/ClubCreationModal/Common/SubmitButton.tsx
  components/ClubCreationModal/Page/AddClubMember.style.ts
  components/ClubCreationModal/Page/AddClubMember.tsx
  components/ClubCreationModal/Page/ClubInfoInput.tsx
  components/ClubCreationModal/Page/ClubKindSelection.tsx
  components/ClubCreationModal/index.tsx
  hooks/index.ts
  hooks/useFetch.tsx
  mocks/handlers/api/club/post.ts
  mocks/handlers/api/user/search/get.ts
  mocks/handlers/index.ts
  store/clubCreation.test.ts
  store/clubCreation.ts
  type/store/clubCreation.ts
Labels: ✨ Feature

#39 🔀 useFetch hook의 타입 수정
  hooks/useFetch.tsx
Labels: 🐞 Bug

#40 🔀 파일 구조 수정
  components/ClubCreationModal/Common/Layout/index.tsx
  components/ClubCreationModal/Common/Layout/style.ts
  components/ClubCreationModal/Common/Member/index.tsx
  components/ClubCreationModal/Common/Member/style.ts
  components/ClubCreationModal/Common/Navigation/index.tsx
  components/ClubCreationModal/Common/Navigation/style.ts
  components/ClubCreationModal/Common/SelectUserList/index.tsx
  components/ClubCreationModal/Common/SelectUserList/style.ts
  components/ClubCreationModal/Common/SubmitButton/index.tsx
  components/ClubCreationModal/Common/SubmitButton/style.ts
  components/ClubCreationModal/Page/AddClubMember.tsx
  components/ClubCreationModal/Page/ClubContent.tsx
  components/ClubCreationModal/Page/ClubImgUpload.tsx
  components/ClubCreationModal/Page/ClubInfoInput.tsx
  components/Common/BannerImg/index.tsx
  components/Common/BannerImg/style.ts
  components/Common/ClubImgs/index.tsx
  components/Common/ClubImgs/style.ts
  components/Common/Input/index.tsx
  components/Common/Input/style.ts
  components/Common/Textarea/index.tsx
  components/Common/Textarea/style.ts
Labels: ♻️ Refactor

#43 🔀 portal에 모달 닫기 기능 추가
  components/ClubCreationModal/index.tsx
  components/Portal/index.tsx
Labels: ✨ Feature

#44 🔀 로그인 상태를 관리하는 커스텀 훅 개발
  hooks/useUser.tsx
  store/index.ts
  store/user.ts
  type/store/user.ts
Labels: ✨ Feature

#45 신청자 명단 관리 store 제작
  store/applicant.ts
  store/index.ts
  type/store/applicant.ts
Labels: ✨ Feature

#14 🔀 Login 모달 퍼블리싱
  assets/svg/GauthLogo.tsx
  assets/svg/LoginLogo.tsx
  assets/svg/index.ts
  components/Login/index.tsx
  components/Login/style.ts
  hooks/index.ts
  hooks/useLogin.tsx
  lib/GauthLoginUrI.tsx
  mocks/handlers/api/auth/post.ts
  mocks/handlers/index.ts
  type/api/TokenType.ts
Labels: ✨ Feature

#42 🔀 Main 페이지 제작
  assets/svg/RightArrowIcon.tsx
  assets/svg/index.ts
  components/ClubList/ClubItem.tsx
  components/ClubList/index.tsx
  components/ClubList/style.ts
  components/MainPage/Banner.tsx
  components/MainPage/NewClub.tsx
  components/MainPage/NewClubItem.tsx
  components/MainPage/index.tsx
  components/MainPage/style.ts
  mocks/handlers/api/club/get.ts
  mocks/handlers/index.ts
  pages/index.tsx
  type/common/ClubListType.ts
  type/common/index.ts
Labels: ✨ Feature

#46 🔀 Header 제작
  assets/svg/Logo.tsx
  assets/svg/index.ts
  components/Header/Profile.tsx
  components/Header/index.tsx
  components/Header/style.ts
  components/Portal/style.ts
  pages/index.tsx
Labels: ✨ Feature

#52 Member Type 수정
  components/MyPage/index.tsx
  type/common/MemberType.ts
Labels: 2️⃣ Priority: Medium, ⚡️ Simple, 🐞 Bug

#48 🔀 ClubCreationModal 생성 버튼 추가
  components/CreateClubBtn/index.tsx
  components/CreateClubBtn/style.ts
  components/MainPage/index.tsx
Labels: ✨ Feature

#50 🔀 NewClubPage 생성
  components/MainPage/NewClub.tsx
  components/NewClubPage/index.tsx
  components/NewClubPage/style.ts
  hooks/useNewClub.tsx
  pages/new/index.tsx
Labels: ✨ Feature

#53 🔀 react-toastify 추가
  hooks/useFetch.tsx
  lib/toastOption.ts
  package.json
  pages/_app.tsx
  type/hooks/useFetch.ts
  yarn.lock
Labels: ✨ Feature

#55 Delete club onChange function
  components/ClubList/index.tsx
Labels: ⚡️ Simple, 🐞 Bug

#47 🔀 DetailPage 추가
  assets/svg/CopyIcon.tsx
  assets/svg/GearIcon.tsx
  assets/svg/ShortcutsIcon.tsx
  assets/svg/index.ts
  components/ClubList/index.tsx
  components/DetailPage/ClubActivity.tsx
  components/DetailPage/ClubMember.tsx
  components/DetailPage/ClubName.tsx
  components/DetailPage/Contact.tsx
  components/DetailPage/Description.tsx
  components/DetailPage/SideBar.tsx
  components/DetailPage/index.tsx
  components/DetailPage/style.ts
  components/MainPage/NewClub.tsx
  mocks/handlers/api/applicant/delete.ts
  mocks/handlers/api/applicant/post.ts
  mocks/handlers/api/club/{club_id}/data.ts
  mocks/handlers/api/club/{club_id}/get.ts
  mocks/handlers/index.ts
  pages/detail/[clubID].tsx
  store/clubDetail.ts
  store/index.ts
  type/common/ClubDetailType.ts
  type/common/ScopeType.ts
  type/common/index.ts
  type/components/ClubDetailSide.ts
Labels: ✨ Feature

#57 🔀 500 에러 기본 메시지 추가
  hooks/useFetch.tsx
Labels: ⚡️ Simple

#59 🔀 토큰 타입 변경
  api/TokenManager.ts
  type/api/TokenManager.ts
Labels: 🐞 Bug

#51 🔀 동아리 신청자 목록 페이지 제작
  assets/svg/MemoPadIcon.tsx
  assets/svg/PersonIcon.tsx
  assets/svg/School.tsx
  assets/svg/SearchIcon.tsx
  assets/svg/index.ts
  components/ApplicantPage/ChoiceUser/index.tsx
  components/ApplicantPage/ChoiceUser/style.ts
  components/ApplicantPage/SelectedUserImg/index.tsx
  components/ApplicantPage/SelectedUserImg/style.ts
  components/ApplicantPage/UserList/UserItem.tsx
  components/ApplicantPage/UserList/index.tsx
  components/ApplicantPage/UserList/style.ts
  components/ApplicantPage/index.tsx
  components/ApplicantPage/style.ts
  components/Common/ClubNav/index.tsx
  components/Common/ClubNav/style.ts
  mocks/handlers/api/applicant/[clubID]/accept/post.ts
  mocks/handlers/api/applicant/[clubID]/get.ts
  mocks/handlers/api/applicant/[clubID]/reject/post.ts
  mocks/handlers/index.ts
  pages/applicant/[clubID].tsx
  type/common/ApplicantListType.ts
  type/common/index.ts
  type/components/ApplicantPage.ts
Labels: ✨ Feature

#61 🔀 중복된 타입 제거
  type/api/TokenType.ts
Labels: ⚡️ Simple

#60 React Portal 스크롤 기능 막기
  components/Portal/index.tsx
  components/Portal/style.ts
Labels: 🐞 Bug

#63 🔀 동아리 생성 모달 버튼 스타일 수정
  components/CreateClubBtn/style.ts
Labels: ⚡️ Simple

#66 🔀 useEffect eslint 에러 수정
  .eslintrc.json
Labels: ⚙ Setting

#56 🔀 Mypage 기능구현 및 디자인 수정
  components/MyPage/ProfileSetting/index.tsx
  components/MyPage/ProfileSetting/style.ts
  components/MyPage/index.tsx
  components/MyPage/style.ts
  mocks/handlers/api/auth/delete.ts
  mocks/handlers/api/user/delete.ts
  mocks/handlers/api/user/patch.ts
  mocks/handlers/index.ts
  pages/my/index.tsx
  type/components/MyPage.ts
Labels: ✨ Feature

#64 🔀 toast 에러 메시지 추가
  components/ClubList/index.tsx
  components/DetailPage/index.tsx
  hooks/useNewClub.tsx
  mocks/handlers/api/club/get.ts
  mocks/handlers/api/club/{club_id}/get.ts
Labels: ⚡️ Simple, ✨ Feature

#62 🔀 동아리 수정 페이지 퍼블리싱
  components/ClubCreationModal/Page/ClubContent.tsx
  components/ClubCreationModal/Page/ClubImgUpload.tsx
  components/ClubEdit/components/ClubImgs/index.tsx
  components/ClubEdit/components/ClubImgs/style.ts
  components/ClubEdit/components/Edit/index.tsx
  components/ClubEdit/components/Edit/style.ts
  components/ClubEdit/components/Notice/ClubLeaveAndDeleteBtn.tsx
  components/ClubEdit/components/Notice/Switch.tsx
  components/ClubEdit/components/Notice/index.tsx
  components/ClubEdit/components/Notice/style.ts
  components/ClubEdit/index.tsx
  components/ClubEdit/style.ts
  components/Common/BannerImg/index.tsx
  components/Common/ConfirmModal/index.tsx
  components/Common/ConfirmModal/style.ts
  components/Common/Textarea/index.tsx
  hooks/useUpload.tsx
  lib/DataInitializer.ts
  mocks/handlers/api/club/[clubID]/close/patch.ts
  mocks/handlers/api/club/[clubID]/delete.ts
  mocks/handlers/api/club/[clubID]/get.ts
  mocks/handlers/api/club/[clubID]/open/patch.ts
  mocks/handlers/api/club/[clubID]/patch.ts
  mocks/handlers/index.ts
  pages/edit/[clubID].tsx
  type/components/ClubEdit.ts
Labels: ✨ Feature

#65 🔀 next-redux-wrapper 설정 코드 레거시 제거
  package.json
  pages/_app.tsx
  store/clubCreation.test.ts
  store/index.ts
  yarn.lock
Labels: ⚡️ Simple

#69 🔀 환경 변수명 수정
  api/TokenManager.ts
Labels: ⚡️ Simple

#70 🔀사용하지 않는 컴포넌트 삭제
  components/MainPage/index.tsx
Labels: ⚡️ Simple

#71 🔀Delete same mocks
  mocks/handlers/api/club/[clubID]/data.ts
  mocks/handlers/api/club/[clubID]/get.ts
  mocks/handlers/api/club/{club_id}/get.ts
Labels: ⚡️ Simple

#72 동아리 모킹 버그 수정
  mocks/handlers/api/club/get.ts
Labels: ⚡️ Simple, 🐞 Bug

#74 🔀Fix 메인 페이지
  components/ClubList/index.tsx
  components/Header/index.tsx
  components/Login/index.tsx
  store/index.ts
  store/loginModal.ts
Labels: 🐞 Bug

#75 🔀 SEO 기능 추가
  components/ClubEdit/index.tsx
  components/DetailPage/index.tsx
  components/MyPage/index.tsx
  components/SEO/index.tsx
  pages/applicant/[clubID].tsx
  pages/index.tsx
  public/favicon.ico
  public/png/CardImage.png
Labels: ✨ Feature

#77 🔀 useFetch 기능 추가
  hooks/useFetch.tsx
Labels: ✨ Feature

#76 불필요한 useUser를 사용하는 컴포넌트 수정
  components/ClubList/index.tsx
  components/CreateClubBtn/index.tsx
Labels: ♻️ Refactor, ⚡️ Simple

#78 🔀 api 요청 header 수정
  api/TokenManager.ts
  api/index.ts
Labels: ⚡️ Simple

#80 유저상태 관련 컴포넌트 수정
  components/ClubList/index.tsx
  components/CreateClubBtn/index.tsx
Labels: ⚡️ Simple

#73 useUser hook 에러 처리 추가
  hooks/useUser.tsx
Labels: ⚡️ Simple

#79 🔀 동아리 생성 후 store 값 초기화 기능 추가
  components/ClubCreationModal/Page/AddClubMember.tsx
  store/clubCreation.test.ts
  store/clubCreation.ts
Labels: ✨ Feature

#83 Interceptors header 변경
  api/index.ts
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, 🐞 Bug

#84 🔀 이미지 업로드 수정
  components/ClubCreationModal/Page/ClubImgUpload.tsx
Labels: 🐞 Bug

#85 🔀 useUser 반환 값 수정
  hooks/useUser.tsx
Labels: ⚡️ Simple

#87 useLogin 성공시 user 요청 함수 추가
  components/Header/index.tsx
  hooks/useLogin.tsx
Labels: ⚡️ Simple

#86 🔀 이미지 업로드 훅 수정
  hooks/useUpload.tsx
  type/hooks/useUpload.ts
Labels: 🐞 Bug

#88 TokenManager 수정
  api/TokenManager.ts
Labels: ✨ Feature

#89 🔀동아리 리스트 컴포넌트에 호버시 커서추가
  components/ClubList/style.ts
Labels: ⚡️ Simple

#96 🔀 동아리 디테일 페이지 undefined query
  components/DetailPage/index.tsx
Labels: 3️⃣ Priority: Low, 🐞 Bug

#90 🔀 refreshToken이 만료 되었을 때의 처리
  api/TokenManager.ts
Labels: ⚡️ Simple

#99 🔀 동아리 디테일 페이지 SSR 적용
  api/TokenManager.ts
  components/DetailPage/index.tsx
  components/SEO/index.tsx
  package.json
  pages/_app.tsx
  pages/detail/[clubID].tsx
  store/clubCreation.test.ts
  store/index.ts
  yarn.lock
Labels: 2️⃣ Priority: Medium, ✨ Feature

#97 🔀 동아리 디테일 페이지 버튼 기능 추가 및 문제 개선
  components/DetailPage/SideBar.tsx
  components/DetailPage/SideBtn.tsx
  components/DetailPage/style.ts
  mocks/handlers/api/club/[clubID]/data.ts
  store/clubDetail.ts
  type/components/ClubDetailSide.ts
Labels: 1️⃣ Priority: High, ✨ Feature, 🐞 Bug

#98 디테일 페이지 next image추가
  components/DetailPage/ClubActivity.tsx
  components/DetailPage/ClubMember.tsx
  components/DetailPage/Contact.tsx
  components/DetailPage/index.tsx
  components/DetailPage/style.ts
  next.config.js
Labels: ⚡️performance

#106 🔀 SSR로 인한 항상 지원 불가 문제 해결
  pages/detail/[clubID].tsx
  store/clubDetail.ts
Labels: 1️⃣ Priority: High, 🐞 Bug

#111 동아리 신청자 리스트 부장에게 권한이 없는 문제 해결
  components/ApplicantPage/UserList/index.tsx
  components/ApplicantPage/index.tsx
  mocks/handlers/api/applicant/[clubID]/get.ts
  type/common/ApplicantListType.ts
Labels: 🐞 Bug

#113 🔀 404 page 제작
  components/NotFoundPage/index.tsx
  components/NotFoundPage/style.ts
  pages/404/index.tsx
  public/png/404.png
Labels: 2️⃣ Priority: Medium, ✨ Feature

#114 🔀 동아리 페이지 리셋 기능 추가
  components/ClubCreationModal/Page/AddClubMember.tsx
  store/clubCreationPage.ts
Labels: 🐞 Bug

#108 🔀 새로고침시 헤더 프로필이 없어지는 문제 해결
  components/Header/Profile.tsx
  components/Header/index.tsx
  hooks/useUser.tsx
  store/user.ts
  type/store/user.ts
Labels: ⚡️ Simple

#107 🔀 디테일페이지 수정
  components/ClubList/index.tsx
  components/ClubList/style.ts
  components/DetailPage/ClubActivity.tsx
  components/DetailPage/ClubMember.tsx
  components/DetailPage/Contact.tsx
  components/DetailPage/SideBar.tsx
  components/DetailPage/style.ts
Labels: ⚡️ Simple

#110 🔀 동아리 멤버 페이지 추가
  components/ClubMemberPage/UserList/UserItem.tsx
  components/ClubMemberPage/UserList/index.tsx
  components/ClubMemberPage/UserList/style.ts
  components/ClubMemberPage/index.tsx
  components/ClubMemberPage/style.ts
  mocks/handlers/api/club-member/[clubID]/get.ts
  mocks/handlers/api/club-member/[clubID]/patch.ts
  mocks/handlers/api/club-member/[clubID]/post.ts
  mocks/handlers/index.ts
  pages/member/[clubID].tsx
  type/common/MemberListType.ts
  type/common/index.ts
  type/components/MemberPage.ts
  type/store/member.ts
Labels: 1️⃣ Priority: High, ✨ Feature

#116 🔀 토큰 재발급 동시 요청 문제 해결
  api/TokenManager.ts
Labels: 1️⃣ Priority: High, 🐞 Bug

#118 🔀 Club Member 페이지 권한 이슈 해결
  components/ClubMemberPage/UserList/UserItem.tsx
Labels: 1️⃣ Priority: High, 🐞 Bug

#119 🔀useUser에 url체크 기능 추가
  components/Header/index.tsx
  components/MyPage/ProfileSetting/index.tsx
  hooks/useLoggedIn.tsx
  hooks/useLogin.tsx
  lib/checkUrlList.ts
Labels: ✨ Feature, 🐞 Bug, 🙋‍♂️ Question

#121 클럽리스트 수정
  components/ClubList/ClubItem.tsx
  components/ClubList/style.ts
Labels: ♻️ Refactor, ⚡️ Simple, ⚡️performance, 🐞 Bug

#122 🔀 동아리 생성 모달 스크롤바 수정
  components/ClubCreationModal/Common/Layout/style.ts
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#123 🔀 TokenManager 조건 수정
  api/TokenManager.ts
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#124 🔀 axios 동시 요청 막기
  api/TokenManager.ts
Labels: 1️⃣ Priority: High, 🐞 Bug

#125 🔀 토큰 재발급 중복 요청 문제 해결
  api/TokenManager.ts
  api/index.ts
Labels: 1️⃣ Priority: High, 🐞 Bug

#120 🔀 MyPage 수정
  components/MyPage/ClubItem/index.tsx
  components/MyPage/ClubItem/style.ts
  components/MyPage/ProfileSetting/index.tsx
  components/MyPage/ProfileSetting/style.ts
  components/MyPage/index.tsx
  components/MyPage/style.ts
  mocks/handlers/api/user/get.ts
  type/common/ProfileType.ts
  type/components/MyPage.ts
Labels: 1️⃣ Priority: High, 🐞 Bug

#126 🔀 토큰 날짜 계산 수정
  api/TokenManager.ts
Labels: 1️⃣ Priority: High, 🐞 Bug

#127 🔀동아리 리스트 border-radius추가
  components/ClubList/style.ts
Labels: ⚡️ Simple

#128 🔀로고 수정
  assets/svg/Logo.tsx
Labels: ⚡️ Simple

#129 🔀useLoggedIn 마운트시 실행하는 fetch on/off기능 추가
  components/Header/index.tsx
  components/MyPage/ProfileSetting/index.tsx
  hooks/useLoggedIn.tsx
  hooks/useLogin.tsx
Labels: ♻️ Refactor, ⚡️ Simple, ✨ Feature

#134 🔀 로그아웃 시 헤더가 바뀌지 않는 이슈 해결
  components/MyPage/ProfileSetting/index.tsx
Labels: 1️⃣ Priority: High, 🐞 Bug

#102 🔀 디테일 페이지 console log 제거
  components/DetailPage/SideBtn.tsx
  components/DetailPage/style.ts
  type/components/ClubDetailSide.ts
Labels: ⚡️ Simple

#137 🔀 토큰 재발급 동시 요청 문제 해결
  api/TokenManager.ts
  api/index.ts
  store/index.ts
  store/reissue.ts
  type/store/reissue.ts
Labels: 1️⃣ Priority: High, 🐞 Bug

#140 🔀 동아리 지원자 목록 페이지에서 undefined 요청을 날리는 문제를 해결했습니다
  components/ApplicantPage/index.tsx
  components/Common/ClubNav/index.tsx
Labels: 3️⃣ Priority: Low, 🐞 Bug

#142 Image 속성 추가
  components/ClubList/ClubItem.tsx
  components/DetailPage/ClubActivity.tsx
  components/DetailPage/index.tsx
  components/DetailPage/style.ts
Labels: ⚡️ Simple

#143 🔀 accessToken 과 accessExp 값이 모두 만료가 되었을 때의 문제 해결
  api/TokenManager.ts
  api/index.ts
  lib/delay.ts
  store/reissue.ts
Labels: 1️⃣ Priority: High, 🐞 Bug

#146 🔀next image에 priority 속성 추가
  components/ClubList/ClubItem.tsx
Labels: ⚡️ Simple

#144 🔀 동아리 리스트 페이지 SSR 적용
  components/ClubList/index.tsx
  pages/detail/[clubID].tsx
  pages/index.tsx
  store/clubList.ts
  store/index.ts
Labels: 2️⃣ Priority: Medium, ✨ Feature

#147 🔀 useLogin routing 방식 수정
  hooks/useLogin.tsx
Labels: 2️⃣ Priority: Medium, 🐞 Bug

#145 🔀confirm modal 스타일 수정
  components/Common/ConfirmModal/style.ts
Labels: ⚡️ Simple

#150 🔀 동아리 수정시 부장이 늘어나는 버그
  lib/DataInitializer.ts
Labels: 2️⃣ Priority: Medium, 🐞 Bug

#153 🔀 선생님 이미지 스타일 수정
  components/DetailPage/style.ts
Labels: 3️⃣ Priority: Low

#155 🔀 header의 유저 정보가 사라지는 문제 해결
  store/index.ts
Labels: 1️⃣ Priority: High, 🐞 Bug

#165 🔀 동아리 페이지 새로고침 시 undefind 쿼리 이슈 해결
  components/ClubMemberPage/index.tsx
Labels: 1️⃣ Priority: High, 🐞 Bug

#154 🔀 동아리 신청자 api 이슈 해결
  components/ApplicantPage/ChoiceUser/index.tsx
  components/ApplicantPage/index.tsx
Labels: 2️⃣ Priority: Medium, 🐞 Bug

#152 🔀 동아리 생성 모달의 자잘한 문제 해결
  components/ClubCreationModal/Page/AddClubMember.tsx
  components/ClubCreationModal/Page/ClubInfoInput.tsx
  components/ClubEdit/components/Notice/style.ts
  hooks/useUpload.tsx
Labels: 3️⃣ Priority: Low

#168 디테일 페이지 멤버 리스트 스타일 수정
  components/DetailPage/style.ts
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#170 🔀 마이페이지에서 디테일 페이지로 가는 기능 추가
  components/MyPage/ClubItem/index.tsx
Labels: ⚡️ Simple, ✨ Feature

#171 🔀 ProfileType 중복 문제
  components/Header/Profile.tsx
  components/Header/index.tsx
  hooks/useLoggedIn.tsx
  store/user.ts
  type/store/user.ts
Labels: 3️⃣ Priority: Low

#172 🔀 동아리 지원 실패 메시지 수정
  components/DetailPage/SideBtn.tsx
Labels: 3️⃣ Priority: Low

#174 🔀 이미지 업로드 필터
  components/MyPage/ProfileSetting/index.tsx
Labels: ⚡️ Simple

#173 🔀 신청자 리스트 클릭 범위 수정
  components/ApplicantPage/SelectedUserImg/style.ts
  components/ApplicantPage/UserList/UserItem.tsx
  components/ApplicantPage/UserList/style.ts
Labels: ⚡️ Simple

#175 🔀 마이페이지 클럽리스트 클릭 범위 수정
  components/MyPage/ClubItem/index.tsx
  components/MyPage/ClubItem/style.ts
Labels: ⚡️ Simple

#179 🔀 동아리 멤버 리스트 옵션 버튼 조건 수정
  components/ClubMemberPage/UserList/UserItem.tsx
Labels: ⚡️ Simple, ⚡️performance

#182 🔀 hooks 폴더 리펙토링
  components/Header/index.tsx
  components/MainPage/NewClub.tsx
  components/MyPage/ProfileSetting/index.tsx
  components/MyPage/index.tsx
  components/NewClubPage/index.tsx
  hooks/index.ts
Labels: ⚡️ Simple, ⚡️performance

#181 🔀 my 페이지의 오류 수정
  components/MyPage/ClubItem/index.tsx
  components/MyPage/ClubItem/style.ts
Labels: 3️⃣ Priority: Low, 🐞 Bug
