Repository GSM-MSG/GCMS-FrontEnd-V2, pull requests merged in 2024-04, with the labels that each got.

#292 🔀 리다이렉트 시키는 GAuth login uri 변경
  lib/GauthLoginUrI.tsx
Labels: 0️⃣ Priority: Critical

#293 🔀 토큰 제거 오류
  api/TokenManager.ts
  api/index.ts
  store/reissue.ts
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#294 🔀 잘못된 url 변경
  components/StatisticsPage/CalendarModal/index.tsx
Labels: 0️⃣ Priority: Critical

#295 🔀 동아리 생성 시 동아리원 선택 이미지 오류
  components/ClubCreationPage/Common/Member/style.ts
Labels: ⚡️ Simple

#296 🔀출석 기능 추가
  assets/svg/Attend_ABSENT.tsx
  assets/svg/Attend_ATTENDED.tsx
  assets/svg/Attend_LATE.tsx
  assets/svg/Attend_REASONABLE_ABSENT.tsx
  assets/svg/Calendar.tsx
  assets/svg/Hand.tsx
  assets/svg/Plus.tsx
  assets/svg/index.ts
  components/ApplicantPage/index.tsx
  components/AttendPage/AttendanceForm.tsx
  components/AttendPage/ChoiceUser/index.tsx
  components/AttendPage/ChoiceUser/style.ts
  components/AttendPage/SelectedUserImg/index.tsx
  components/AttendPage/SelectedUserImg/style.ts
  components/AttendPage/UserList/UserItem.tsx
  components/AttendPage/UserList/index.tsx
  components/AttendPage/UserList/style.ts
  components/AttendPage/index.tsx
  components/AttendPage/style.ts
  components/Common/ClubNav/index.tsx
  components/Common/Input/index.tsx
  pages/attend/[clubID].tsx
  store/attend.ts
  type/common/AttendListType.ts
  type/common/AttendMemberType.ts
  type/common/clubMemberListType.ts
  type/components/AttendPage.ts
  type/store/applicant.ts
Labels: 1️⃣ Priority: High, ✨ Feature

#302 🔀 클럽 생성 시 배너 이미지 권장 사이즈 설명 추가
  components/Common/BannerImg/index.tsx
  components/Common/BannerImg/style.ts
  components/DetailPage/SideBar.tsx
Labels: ⚡️ Simple

#301 🔀 노션 보러가기 클릭 시 새창 띄우기
  components/DetailPage/SideBar.tsx
Labels: ⚡️ Simple

#303 🔀 출석 페이지 수정
  components/AttendPage/AttendanceForm.tsx
  components/AttendPage/ChoiceUser/index.tsx
  components/AttendPage/index.tsx
Labels: 0️⃣ Priority: Critical

#305 🔀 Deploy
  api/TokenManager.ts
  api/index.ts
  components/AttendPage/AttendanceForm.tsx
  components/AttendPage/ChoiceUser/index.tsx
  components/AttendPage/index.tsx
  components/Common/BannerImg/index.tsx
  components/Common/BannerImg/style.ts
  components/DetailPage/SideBar.tsx
  store/reissue.ts
Labels: 🌏 Deploy
